(() => {
  const tr=(en,ar)=>document.documentElement.lang==='ar'?ar:en;
  const intents={
    plan:{title:['A routine you can keep.','روتين يمكنك الاستمرار عليه.'],body:['Turn a goal into learning, practice and review sessions that fit your available time.','حوّل هدفك إلى جلسات تعلم وتطبيق ومراجعة تناسب وقتك المتاح.'],steps:[['Choose a goal','اختر هدفاً'],['Preview the schedule','عاين الجدول'],['Start one session','ابدأ جلسة واحدة']],name:['Open StudyFlow','افتح منظّم التعلم'],path:'studyflow.html#planner'},
    focus:{title:['One task. Room to focus.','مهمة واحدة. ومساحة للتركيز.'],body:['Set a manageable session, name one task, and take a deliberate break afterward.','حدّد جلسة مناسبة وسمّ مهمة واحدة، ثم خذ استراحة مقصودة بعدها.'],steps:[['Name one task','سمّ مهمة واحدة'],['Set the time','حدّد الوقت'],['Focus, then rest','ركّز ثم استرح']],name:['Open Focus Room','افتح مساحة التركيز'],path:'focus.html'},
    json:{title:['See the structure clearly.','شاهد البنية بوضوح.'],body:['Import or paste JSON, check it, then format or compact a clean result. Everything runs in your browser.','استورد JSON أو الصقه، افحصه ثم نسّقه أو اضغطه. تتم المعالجة داخل المتصفح.'],steps:[['Add JSON','أضف JSON'],['Validate and format','افحص ونسّق'],['Copy or export','انسخ أو صدّر']],name:['Open JSON Studio','افتح استوديو JSON'],path:'json.html'},
    hash:{title:['Compare against a trusted source.','قارن بمصدر موثوق.'],body:['Calculate a file or text fingerprint and compare it with the expected digest. A match checks integrity, not safety.','احسب بصمة ملف أو نص وقارنها بالقيمة المتوقعة. التطابق يفحص سلامة النسخة ولا يثبت أمانها.'],steps:[['Choose a file or text','اختر ملفاً أو نصاً'],['Calculate the digest','احسب البصمة'],['Compare the source','قارن بالمصدر']],name:['Open File Fingerprint','افتح بصمة الملفات'],path:'hash.html'},
    text:{title:['Make your text easier to use.','اجعل نصّك أسهل للاستخدام.'],body:['Check words and reading time, clean excess spaces, remove exact duplicate lines and keep a copy.','راجع عدد الكلمات ووقت القراءة، نظّف المسافات الزائدة واحذف الأسطر المتطابقة واحتفظ بنسخة.'],steps:[['Paste your text','الصق النص'],['Review before and after','راجع قبل وبعد'],['Undo or export','تراجع أو صدّر']],name:['Open Text Studio','افتح استوديو النصوص'],path:'text.html'}
  };
  let intent='plan';
  const box=document.getElementById('intent-result'),make=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
  function render(){document.querySelectorAll('.tool-orientation').forEach(e=>e.setAttribute('aria-label',tr('Tool help','مساعدة الأداة')));if(!box)return;box.setAttribute('aria-label',tr('Suggested next step','الخطوة القادمة المقترحة'));const c=intents[intent];box.replaceChildren(make('h3',tr(...c.title)),make('p',tr(...c.body)));const list=document.createElement('ul');for(const step of c.steps)list.append(make('li',tr(...step)));const link=make('a',tr(...c.name)+' ↗');link.href=c.path;box.append(list,link);document.querySelectorAll('[data-intent]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.intent===intent)));}
  document.querySelectorAll('[data-intent]').forEach(b=>b.addEventListener('click',()=>{intent=b.dataset.intent;render();}));
  document.querySelectorAll('[data-guide-open]').forEach(b=>b.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('biuret:guide-open',{detail:{topic:b.dataset.guideTopic||''}}))));
  const current=(location.pathname.split('/').pop()||'index.html');document.querySelectorAll('.top nav a').forEach(a=>{if((current==='software.html'&&a.getAttribute('href')==='software.html')||(current==='index.html'&&a.getAttribute('href')==='#applications'))a.setAttribute('aria-current','page');});
  const hero=document.querySelector('.pg-hero'),storage=document.querySelector('.storage-bar');if(hero&&storage)hero.after(storage);
  new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});render();
})();
