(() => {
  const form=document.getElementById('plan-form');if(!form)return;
  const $=id=>document.getElementById(id),locale=()=>document.documentElement.lang,tr=(en,ar)=>locale()==='ar'?ar:en;
  const kind={learn:['Learn','تعلّم'],practice:['Practice','تطبيق'],review:['Review','مراجعة'],project:['Final project','المشروع النهائي']};
  const number=n=>new Intl.NumberFormat(locale()).format(n),formatDate=d=>new Intl.DateTimeFormat(locale(),{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(d+'T12:00:00'));
  let plan=null,config=null,activeId=null,persistedConfig=null,completed=new Set(),scheduleMeta=null,proposal=null,visible=8;
  const workloadConfig=c=>{if(!c)return null;const copy={...c};delete copy.deadline;return JSON.stringify(copy);};
  const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  $('start').value=WorkspaceStore.localDay();
  function customFields(){const custom=$('template').value==='custom';$('custom-fields').hidden=!custom;$('custom-goal').required=$('custom-topics').required=custom;const workload={beginner:[60,60,20],intermediate:[40,75,25],advanced:[30,90,30]}[$('level').value];$('custom-estimate').textContent=tr(`Per topic: ${workload[0]} learning, ${workload[1]} practice and ${workload[2]} review minutes, plus a 90-minute final deliverable. These estimates use your selected level; no lessons or AI-generated content are included.`,`لكل موضوع: ${workload[0]} دقيقة تعلم، ${workload[1]} تطبيق، ${workload[2]} مراجعة، إضافة إلى 90 دقيقة للنتيجة النهائية. هذه تقديرات حسب المستوى؛ لا تتضمن دروساً أو محتوى مولداً بالذكاء الاصطناعي.`);$('deadline').min=$('start').value;}
  $('template').addEventListener('change',customFields);$('level').addEventListener('change',customFields);$('start').addEventListener('change',customFields);customFields();
  function invalidate(){proposal=null;$('replan-preview').hidden=true;$('replan-apply').disabled=true;$('replan-status').textContent='';}
  function deadlineText(value){if(value.complete)return tr('All sessions are marked complete.','حدّدت جميع الجلسات كمنجزة.');if(!value.target)return tr('No target date set.','لم تحدّد موعداً مستهدفاً.');return value.late?tr(`Target: ${formatDate(value.target)}. Current estimated finish: ${formatDate(value.finish)}. This routine does not meet the target. Increase available time or study days, reduce scope, or choose a later target.`,`الموعد المستهدف: ${formatDate(value.target)}. النهاية التقديرية: ${formatDate(value.finish)}. هذا الروتين لا يحقق الموعد؛ زد الوقت أو أيام الدراسة، أو قلّل النطاق، أو اختر موعداً لاحقاً.`):tr(`Target: ${formatDate(value.target)}. Estimated finish: ${formatDate(value.finish)}. The current routine fits the target; completion still depends on your work.`,`الموعد المستهدف: ${formatDate(value.target)}. النهاية التقديرية: ${formatDate(value.finish)}. الروتين الحالي يناسب الموعد؛ يبقى الإنجاز معتمداً على عملك.`);}
  function progress(){
    $('study-progress').max=plan.sessions.length;$('study-progress').value=completed.size;$('study-progress-label').textContent=tr(`${number(completed.size)} / ${number(plan.sessions.length)} sessions checked`,`${number(completed.size)} / ${number(plan.sessions.length)} جلسة محددة كمنجزة`);
    const info=LearningPlanner.deadline(plan,[...completed]);$('deadline-feedback').hidden=!info.target;$('deadline-feedback').textContent=deadlineText(info);$('deadline-feedback').dataset.tone=info.late?'late':'ready';$('replan-open').disabled=info.complete;
    const target=$('today-step'),next=WorkspaceStore.nextSessions(plan,[...completed]);target.replaceChildren(node('h4',tr('What should I study today?','ماذا أدرس اليوم؟')));
    const session=next.overdue[0]||next.today[0]||next.next;
    target.append(node('p',next.complete?tr('All sessions checked. Reflect on your final result.','حدّدت جميع الجلسات كمنجزة. راجع نتيجتك النهائية.'):next.overdue.length?tr('Begin with one unfinished session, or preview a new schedule below.','ابدأ بجلسة غير مكتملة، أو اعرض جدولاً جديداً أدناه.'):next.today.length?tr('Your next unfinished step today:','خطوتك التالية غير المكتملة اليوم:'):tr('Your next scheduled session:','جلستك التالية المجدولة:')));
    if(session){target.append(node('p',formatDate(session.date)+' · '+kind[session.kind][locale()==='en'?0:1]+' · '+session.topic+tr(` · ${session.minutes} min`,` · ${session.minutes} دقيقة`)));const link=node('a',tr('Open Focus Room ↗','افتح مساحة التركيز ↗'),'secondary');link.href='focus.html';target.append(link);}
  }
  function savingState(){const saved=PlaygroundWorkspace.read();$('plan-save').disabled=!saved;$('plan-save').textContent=activeId?tr('Update saved plan','حدّث الخطة المحفوظة'):tr('Save plan on this device','احفظ الخطة على الجهاز');if(!saved)$('plan-save-status').textContent=tr('Enable device saving at the top to save this plan and its schedule.','فعّل الحفظ أعلى الصفحة للاحتفاظ بالخطة وجدولها.');}
  function saveCheck(index,checked){
    invalidate();if(!activeId)return;
    try{PlaygroundWorkspace.update(data=>{const saved=data.plans.find(p=>p.id===activeId);if(!saved)throw Error('missing');const set=new Set(saved.completed);checked?set.add(index):set.delete(index);saved.completed=[...set].sort((a,b)=>a-b);saved.updatedAt=new Date().toISOString();completed=new Set(saved.completed);return data;});$('plan-save-status').textContent=tr('Progress saved on this device.','حُفظ التقدم على هذا الجهاز.');document.dispatchEvent(new Event('playground:workspace'));}
    catch{$('plan-save-status').textContent=tr('This check is only in this tab; saving failed. Download your checklist or save again.','هذه العلامة في التبويب فقط؛ تعذّر الحفظ. نزّل قائمة الإنجاز أو احفظ مجدداً.');}
  }
  function renderProposal(){
    if(!proposal)return;
    const proposed=LearningPlanner.restorePlan({config,schedule:proposal.metadata},locale(),StudyFlowCatalog),info=LearningPlanner.deadline(proposed,[...completed]);
    const changed=proposed.sessions.filter((s,i)=>!completed.has(i)&&s.date!==plan.sessions[i].date).length;
    $('replan-preview').hidden=false;$('replan-summary').textContent=tr(`Unfinished session dates changing: ${changed}. Checked sessions retaining their dates: ${completed.size}. Estimated minutes remaining: ${info.remainingMinutes}.`,`ستتغير تواريخ ${changed} جلسة غير مكتملة. تبقى تواريخ ${completed.size} جلسة محددة كمنجزة. المتبقي ${info.remainingMinutes} دقيقة تقديرية.`);
    $('replan-deadline').textContent=info.target?deadlineText(info):tr('Estimated finish: ','النهاية التقديرية: ')+formatDate(info.finish);
    const dates=[...new Set(proposed.sessions.filter((s,i)=>!completed.has(i)).map(s=>s.date))].sort();$('replan-days').replaceChildren();
    for(const date of dates){const rows=proposed.sessions.filter((s,i)=>!completed.has(i)&&s.date===date);$('replan-days').append(node('li',formatDate(date)+tr(` · ${rows.length} sessions · ${rows.reduce((n,s)=>n+s.minutes,0)} min`,` · ${rows.length} جلسة · ${rows.reduce((n,s)=>n+s.minutes,0)} دقيقة`)));}
    $('replan-apply').disabled=false;
  }
  function render(){
    if(!plan)return;$('plan-empty').hidden=true;$('plan-output').hidden=false;
    const days=[...new Set(plan.sessions.map(s=>s.date))].sort(),heading=$('result-heading');heading.replaceChildren(node('h3',tr('Your plan, one step at a time.','خطتك، خطوة بخطوة.')),
      node('p',tr(`${number(plan.sessions.length)} sessions · ${number(days.length)} study days · ${number(plan.sessions.reduce((n,s)=>n+s.minutes,0))} estimated minutes`,`${number(plan.sessions.length)} جلسة · ${number(days.length)} يوم دراسة · ${number(plan.sessions.reduce((n,s)=>n+s.minutes,0))} دقيقة تقديرية`)),
      node('p',tr('Planned finish: ','النهاية المجدولة: ')+formatDate(days.at(-1))),node('p',plan.project));
    if(config.template==='custom')heading.append(node('p',tr('Custom topics and goal are kept exactly as entered; the interface supports both languages.','تُعرض مواضيعك وهدفك كما أدخلتها؛ تدعم الواجهة اللغتين.'),'small muted'));
    if(scheduleMeta)heading.append(node('p',tr('Latest rescheduling starts from: ','آخر إعادة جدولة تبدأ من: ')+formatDate(scheduleMeta.from),'small muted'));
    $('schedule').replaceChildren();
    for(const date of days.slice(0,visible)){const li=node('li');li.append(node('h4',formatDate(date)));
      plan.sessions.forEach((session,index)=>{if(session.date!==date)return;const row=node('label',undefined,'session'),check=node('input');check.type='checkbox';check.checked=completed.has(index);row.classList.toggle('done',check.checked);check.setAttribute('aria-label',tr('Mark complete: ','حدّد كمنجز: ')+session.topic+' · '+kind[session.kind][locale()==='en'?0:1]+' · '+session.part);check.addEventListener('change',()=>{check.checked?completed.add(index):completed.delete(index);saveCheck(index,check.checked);row.classList.toggle('done',check.checked);progress();});
        const topic=node('span'),type=node('b',kind[session.kind][locale()==='en'?0:1]+': ','kind');topic.append(type,document.createTextNode(session.topic));if(session.parts>1)topic.append(document.createTextNode(tr(` (part ${number(session.part)}/${number(session.parts)})`,` (الجزء ${number(session.part)}/${number(session.parts)})`)));row.append(check,topic,node('small',number(session.minutes)+tr(' min',' دقيقة')));li.append(row);
      });$('schedule').append(li);
    }
    $('more').hidden=visible>=days.length;progress();savingState();renderProposal();
  }
  function inputConfig(){const c={template:$('template').value,level:$('level').value,minutes:Number($('minutes').value),days:[...form.querySelectorAll('[name=day]:checked')].map(i=>Number(i.value)),start:$('start').value};if($('deadline').value)c.deadline=$('deadline').value;if(c.template==='custom')c.custom={goal:$('custom-goal').value.trim(),topics:$('custom-topics').value.split(/\r?\n/).map(t=>t.trim()).filter(Boolean)};return LearningPlanner.normalize(c);}
  function configError(error){$('plan-status').textContent=error.message==='duplicate-topics'?tr('Each topic must be unique. Remove duplicate topic lines.','يجب أن يكون كل موضوع مختلفاً. احذف الأسطر المكررة.'):error.message==='custom'?tr('Enter a clear final result and 1–8 unique topics, one per line (up to 100 characters each).','اكتب نتيجة نهائية واضحة ومن 1 إلى 8 مواضيع مختلفة، كل موضوع في سطر حتى 100 حرف.'):error.message==='deadline'?tr('Choose a target date on or after the start date.','اختر موعداً مستهدفاً يساوي تاريخ البداية أو يأتي بعده.'):tr('Check study days, dates and your daily time (15–120 whole minutes).','راجع أيام الدراسة والتواريخ والوقت اليومي (عدد صحيح من 15 إلى 120 دقيقة).');}
  form.addEventListener('submit',event=>{event.preventDefault();try{const next=inputConfig(),generated=LearningPlanner.createPlan({...next,locale:locale()},StudyFlowCatalog);const changed=JSON.stringify(next)!==JSON.stringify(config),targetOnly=changed&&workloadConfig(next)===workloadConfig(config);if(changed)invalidate();if(changed&&!targetOnly){completed.clear();scheduleMeta=null;activeId=null;persistedConfig=null;const url=new URL(location.href);url.searchParams.delete('plan');history.replaceState(null,'',url);$('plan-save-status').textContent='';}config=next;plan=scheduleMeta?LearningPlanner.restorePlan({config,schedule:scheduleMeta},locale(),StudyFlowCatalog):generated;visible=8;if(next.template==='custom'&&!$('plan-name').value.trim())$('plan-name').value=next.custom.goal.slice(0,80);$('replan-from').value=[WorkspaceStore.localDay(),config.start].sort().at(-1);$('replan-from').min=config.start;render();$('plan-status').textContent=targetOnly?tr('Target changed in this preview; your checks are preserved. Save the plan to retain the new target.','تغير الموعد في المعاينة مع الحفاظ على الإنجاز. احفظ الخطة للاحتفاظ بالموعد الجديد.'):activeId?tr('Saved plan ready.','الخطة المحفوظة جاهزة.'):tr('Plan ready. Save it below to keep your progress.','الخطة جاهزة. احفظها أدناه للاحتفاظ بتقدمك.');$('result-heading').focus();}catch(error){configError(error);}});
  $('plan-save').addEventListener('click',()=>{if(!plan)return;if(!$('plan-name').value.trim()){$('plan-save-status').textContent=tr('Give your plan a name first.','أعطِ خطتك اسماً أولاً.');$('plan-name').focus();return;}
    try{let savedId;PlaygroundWorkspace.update(data=>{const existing=data.plans.find(p=>p.id===activeId);if(!existing&&data.plans.length>=20)throw Error('limit');const saved=WorkspaceStore.makePlan(config,$('plan-name').value,LearningPlanner.createPlan({...config,locale:locale()},StudyFlowCatalog),existing);saved.completed=[...completed];if(scheduleMeta){saved.schedule=scheduleMeta;saved.engine=2;}else delete saved.schedule;savedId=saved.id;data.plans=existing?data.plans.map(p=>p.id===saved.id?saved:p):[...data.plans,saved];return data;});activeId=savedId;persistedConfig=JSON.stringify(config);const url=new URL(location.href);url.searchParams.set('plan',savedId);history.replaceState(null,'',url);$('plan-save-status').textContent=tr('Plan and schedule saved. Future checks save automatically.','حُفظت الخطة وجدولها. تُحفظ علامات الإنجاز التالية تلقائياً.');$('plan-status').textContent=tr('Your saved plan is ready.','خطتك المحفوظة جاهزة.');savingState();document.dispatchEvent(new Event('playground:workspace'));}catch{$('plan-save-status').textContent=tr('Could not save. Check the 20-plan limit or browser storage. Previous saved work is unchanged.','تعذّر الحفظ. تحقق من حد 20 خطة أو التخزين. أعمالك السابقة لم تتغير.');}
  });
  $('replan-from').addEventListener('input',invalidate);
  $('replan-open').addEventListener('click',()=>{invalidate();try{const from=$('replan-from').value,result=LearningPlanner.reschedule({...config,locale:locale()},StudyFlowCatalog,[...completed],from,plan.sessions.map(s=>s.date));proposal={metadata:result.metadata,snapshot:[...completed].sort((a,b)=>a-b),config:JSON.stringify(config)};renderProposal();$('replan-status').textContent=tr('Preview only. Your saved schedule has not changed.','معاينة فقط. لم يتغير جدولك المحفوظ.');}catch{$('replan-status').textContent=tr('Could not reschedule. Choose a valid date on or after the original start, with enough calendar space before year 2101.','تعذرت إعادة الجدولة. اختر تاريخاً صالحاً بعد البداية أو مساوياً لها مع مساحة زمنية كافية قبل عام 2101.');}});
  $('replan-apply').addEventListener('click',()=>{if(!proposal)return;try{const snapshot=JSON.stringify(proposal.snapshot);if(snapshot!==JSON.stringify([...completed].sort((a,b)=>a-b))||proposal.config!==JSON.stringify(config))throw Error('stale');const meta=proposal.metadata,newPlan=LearningPlanner.restorePlan({config,schedule:meta},locale(),StudyFlowCatalog);
      if(activeId)PlaygroundWorkspace.update(data=>{const saved=data.plans.find(p=>p.id===activeId);if(!saved||JSON.stringify(saved.completed)!==snapshot||JSON.stringify(saved.config)!==persistedConfig)throw Error('stale');saved.config=config;saved.schedule=meta;saved.engine=2;saved.updatedAt=new Date().toISOString();return data;});
      if(activeId)persistedConfig=JSON.stringify(config);scheduleMeta=meta;plan=newPlan;visible=8;invalidate();render();$('replan-status').textContent=activeId?tr('New schedule saved. Completion checks and completed-session dates are preserved.','حُفظ الجدول الجديد مع الحفاظ على علامات الإنجاز وتواريخ الجلسات المحددة كمنجزة.'):tr('New schedule applied in this tab. Save the plan to retain it.','طُبّق الجدول في هذا التبويب. احفظ الخطة للاحتفاظ به.');if(activeId)document.dispatchEvent(new Event('playground:workspace'));
    }catch{invalidate();$('replan-status').textContent=tr('Could not apply: saved progress changed, or storage is unavailable. Reload the saved plan and preview again. Your saved schedule was not replaced.','تعذّر الاعتماد: تغيّر التقدم المحفوظ أو التخزين غير متاح. أعد تحميل الخطة واعرض المعاينة مجدداً. لم نستبدل جدولك المحفوظ.');}});
  $('more').addEventListener('click',()=>{visible+=8;render();});
  function syncForm(){for(const key of ['template','level','minutes','start'])$(key).value=config[key];$('deadline').value=config.deadline||'';form.querySelectorAll('[name=day]').forEach(i=>i.checked=config.days.includes(Number(i.value)));$('custom-goal').value=config.custom?.goal||'';$('custom-topics').value=config.custom?.topics.join('\n')||'';customFields();$('replan-from').value=[WorkspaceStore.localDay(),config.start].sort().at(-1);$('replan-from').min=config.start;}
  function load(saved){config=saved.config;persistedConfig=JSON.stringify(saved.config);activeId=saved.id;scheduleMeta=saved.schedule||null;completed=new Set(saved.completed);plan=LearningPlanner.restorePlan(saved,locale(),StudyFlowCatalog);$('plan-name').value=saved.name;syncForm();invalidate();render();$('plan-status').textContent=tr('Saved plan restored. Continue from your next unfinished session.','استُعيدت خطتك. تابع من الجلسة التالية غير المكتملة.');}
  document.addEventListener('playground:language',()=>{customFields();if(plan){plan=LearningPlanner.restorePlan({config,schedule:scheduleMeta},locale(),StudyFlowCatalog);render();$('plan-status').textContent='';$('plan-save-status').textContent='';$('replan-status').textContent='';savingState();}});
  document.addEventListener('playground:workspace',savingState);
  window.addEventListener('storage',e=>{if(e.key!==WorkspaceStore.KEY&&e.key!==null)return;const saved=PlaygroundWorkspace.read()?.plans.find(p=>p.id===activeId);if(saved)load(saved);else if(activeId){activeId=null;persistedConfig=null;invalidate();savingState();}});
  const restoreId=new URLSearchParams(location.search).get('plan');if(restoreId){const saved=PlaygroundWorkspace.read()?.plans.find(p=>p.id===restoreId);if(saved)load(saved);else $('plan-status').textContent=tr('This plan is not saved in this browser. Open My Work or restore a backup.','هذه الخطة غير محفوظة في هذا المتصفح. افتح أعمالي أو استعد نسخة احتياطية.');}
  function exportFile(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('calendar').addEventListener('click',()=>{if(!plan)return;exportFile(Workbench.planCalendar(plan),'studyflow-calendar.ics','text/calendar;charset=utf-8');$('plan-status').textContent=tr('Import these all-day reminders yourself. After rescheduling, remove obsolete calendar reminders yourself; a new import does not delete them.','استورد تذكيرات اليوم الكامل بنفسك. بعد إعادة الجدولة، احذف التذكيرات القديمة بنفسك؛ الاستيراد الجديد لا يحذفها.');});
  $('plan-notes').addEventListener('click',()=>{if(!plan)return;exportFile([plan.project,'',...plan.sessions.map((s,i)=>`${completed.has(i)?'[x]':'[ ]'} ${s.date} · ${kind[s.kind][locale()==='en'?0:1]} · ${s.topic} · ${s.minutes} min`)].join('\n'),'studyflow-checklist.txt','text/plain;charset=utf-8');});
  $('download').addEventListener('click',()=>{if(!plan)return;exportFile(JSON.stringify({format:'biuret-playground-preview-v1',...plan},null,2),'studyflow-plan-preview.json','application/json');$('plan-status').textContent=tr('Preview downloaded. Use My Work for a restorable workspace backup.','نُزّلت المعاينة. استخدم أعمالي لتنزيل نسخة أعمال قابلة للاستعادة.');});
})();
