const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const model=require('../workspace-store.js'),planner=require('../planner.js'),context={window:{}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../catalog.js'),'utf8'),context);
const catalog=JSON.parse(JSON.stringify(context.window.StudyFlowCatalog));
function memory(){let value=null;return {getItem:()=>value,setItem:(k,v)=>{value=v;},removeItem:()=>{value=null;}};}
function plan(name='Python plan'){const config={template:'python',level:'beginner',minutes:45,days:[1,3,5],start:'2026-10-09'},generated=planner.createPlan({...config,locale:'en'},catalog);return model.makePlan(config,name,generated);}
function backup(){return {...model.empty(),plans:[plan()]};}
test('Storage is opt-in; enabling persists only an empty workspace',()=>{const storage=memory(),s=model.connect(storage,planner,catalog);assert.equal(s.read(),null);assert.throws(()=>s.update(x=>x),/disabled/);assert.equal(storage.getItem(),null);s.enable();assert.deepEqual(s.read(),model.empty());});
test('Plans and checks survive reconnect; language uses the same session order',()=>{const storage=memory(),s=model.connect(storage,planner,catalog),p=plan();p.completed=[0,2];s.enable();s.update(x=>({...x,plans:[p]}));const read=model.connect(storage,planner,catalog).read();assert.deepEqual(read.plans[0].completed,[0,2]);const ar=planner.createPlan({...p.config,locale:'ar'},catalog),en=planner.createPlan({...p.config,locale:'en'},catalog);assert.deepEqual(ar.sessions.map(s=>[s.kind,s.date,s.part]),en.sessions.map(s=>[s.kind,s.date,s.part]));});
test('Invalid backups never overwrite saved work',()=>{const storage=memory(),s=model.connect(storage,planner,catalog);s.enable();s.restore(backup());const before=storage.getItem();for(const value of ['{}','not JSON','{"format":"biuret-playground-workspace","version":99}', ' '.repeat(1048577)])assert.throws(()=>model.parse(value,planner,catalog));const bad=backup();bad.plans[0].completed=[-1];assert.throws(()=>s.restore(bad));assert.equal(storage.getItem(),before);});
test('Untrusted schema, limits, invalid dates and altered schedules are rejected',()=>{for(const mutate of [b=>b.plans[0].config.start='2026-02-30',b=>b.plans[0].config.days=[1,1],b=>b.plans[0].signature+='x',b=>b.plans[0].completed=[9999],b=>b.plans[0].completed=[1,1],b=>b.plans[0].name='x'.repeat(81),b=>b.favorites=['../secret'],b=>b.goal=21,b=>b.sessions=[{id:'session_1',task:'ok',minutes:0,at:new Date().toISOString()}]]){const b=backup();mutate(b);assert.throws(()=>model.validate(b,planner,catalog));}});
test('Quota failure is atomic and blocked/corrupt storage is not silently reset',()=>{const storage=memory(),s=model.connect(storage,planner,catalog);s.enable();const before=storage.getItem();storage.setItem=()=>{throw Error('quota');};assert.throws(()=>s.restore(backup()),/quota/);assert.equal(storage.getItem(),before);const broken=model.connect({getItem:()=>'{broken',setItem:()=>assert.fail('overwrite')},planner,catalog);assert.equal(broken.read(),null);assert.throws(()=>broken.enable());assert.ok(broken.issue);});
test('Each mutation reads the latest data across connected tabs',()=>{const storage=memory(),a=model.connect(storage,planner,catalog),b=model.connect(storage,planner,catalog);a.enable();a.restore(backup());b.update(x=>({...x,favorites:['focus']}));a.update(x=>({...x,goal:7}));assert.deepEqual(b.read().favorites,['focus']);assert.equal(b.read().goal,7);assert.equal(b.read().plans.length,1);});
test('Merge retains plans and both progress sets; repeated import does not duplicate logs',()=>{const a=backup(),b=structuredClone(a);a.plans[0].completed=[0];b.plans[0].completed=[1];b.sessions=[{id:'session_1',task:'Practice',minutes:25,at:new Date().toISOString()}];const merged=model.merge(a,b);assert.deepEqual(merged.plans[0].completed,[0,1]);assert.equal(model.merge(merged,b).sessions.length,1);const conflict=structuredClone(b);conflict.sessions[0].minutes=45;assert.throws(()=>model.merge(merged,conflict),/conflict/);});
test('Capacity limits prevent automatic deletion of older saved data',()=>{const storage=memory(),s=model.connect(storage,planner,catalog);s.enable();const b=backup();b.plans=Array.from({length:20},(_,i)=>({...b.plans[0],id:'plan_id_'+i}));s.restore(b);const before=storage.getItem();assert.throws(()=>s.restore(backup()));assert.equal(storage.getItem(),before);});
test('Next step distinguishes overdue, today, future and completed sessions',()=>{const p={sessions:[{date:'2026-10-08'},{date:'2026-10-09'},{date:'2026-10-12'}]};assert.equal(model.nextSessions(p,[],'2026-10-09').overdue.length,1);const next=model.nextSessions(p,[0],'2026-10-09');assert.equal(next.today[0].index,1);assert.equal(next.next.index,2);assert.equal(model.nextSessions(p,[0,1,2],'2026-10-09').complete,true);});
test('Focus summary uses local calendar days and excludes future records',()=>{const now=new Date(2026,9,9,12),sessions=[{at:new Date(2026,9,9,10).toISOString(),minutes:25},{at:new Date(2026,9,3,0).toISOString(),minutes:15},{at:new Date(2026,9,2,23,59).toISOString(),minutes:45},{at:new Date(2026,9,9,13).toISOString(),minutes:60}];assert.deepEqual(model.summary(sessions,now),{today:1,todayMinutes:25,week:2,weekMinutes:40});});
